# Generated by Django 5.2.17 on 2026-10-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Obra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("direccion", models.CharField(max_length=250)),
                ("entidad_responsable", models.CharField(max_length=200)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("asignada", "asignada"),
                            ("iniciada", "iniciada"),
                            ("finalizada", "finalizada"),
                            ("entregada", "entregada"),
                        ],
                        default="asignada",
                        max_length=20,
                    ),
                ),
                ("avance", models.PositiveIntegerField(default=0)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
