server:
  port: 8080

spring:
  application:
    name: urbanalert-users
  jpa:
    open-in-view: false
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health
